import { db } from "@workspace/db";
import { propertiesTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const OWNER_ID = "seed_owner_bloq5";

/* ──────────────────────────────────────────────────────────────
   Données fictives — locations canadiennes toutes catégories
──────────────────────────────────────────────────────────────── */

const seed = [

  /* ── APPARTEMENTS ── */
  {
    title: "Appartement 4½ lumineux avec balcon",
    description: "Bel appartement rénové au 3e étage avec balcon sud. Cuisine ouverte, planchers de bois franc, stationnement inclus.",
    type: "apartment" as const, city: "Montréal", address: "2345 Rue Sherbrooke Est", country: "Canada",
    price: "1750.00", bedrooms: 2, bathrooms: 1, area: "72.00", status: "available" as const, isFeatured: true,
    amenities: ["Balcon", "Stationnement", "Buanderie", "Internet inclus"],
    images: ["https://picsum.photos/seed/apt1/800/500"],
    availableDates: ["2026-06-01", "2026-06-15"],
    nearbyPlaces: ["Métro Frontenac (350m)", "Marché Jean-Talon (2km)", "Parc La Fontaine (1,2km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Studio meublé centre-ville Montréal",
    description: "Studio moderne entièrement meublé, idéal pour jeune professionnel. Accès facile au métro, tout inclus sauf électricité.",
    type: "apartment" as const, city: "Montréal", address: "1200 Boul. René-Lévesque Ouest", country: "Canada",
    price: "1250.00", bedrooms: 0, bathrooms: 1, area: "35.00", status: "available" as const, isFeatured: true,
    amenities: ["Meublé", "Climatisation", "Internet inclus", "Sécurité 24h"],
    images: ["https://picsum.photos/seed/apt2/800/500"],
    availableDates: ["2026-05-15"],
    nearbyPlaces: ["Métro Bonaventure (200m)", "Centre Eaton (500m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 3½ Plateau Mont-Royal",
    description: "Charmant appartement au cœur du Plateau. Très lumineux, haut plafond, cachet montréalais authentique.",
    type: "apartment" as const, city: "Montréal", address: "4512 Rue Saint-Denis", country: "Canada",
    price: "1450.00", bedrooms: 1, bathrooms: 1, area: "55.00", status: "available" as const, isFeatured: false,
    amenities: ["Balcon", "Buanderie commune", "Cave"],
    images: ["https://picsum.photos/seed/apt3/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["Parc Laurier (300m)", "Métro Mont-Royal (500m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Grand 5½ avec garage — Rosemont",
    description: "Spacieux appartement familial avec garage simple et grande cour arrière. Idéal pour famille avec enfants.",
    type: "apartment" as const, city: "Montréal", address: "3280 Rue Masson", country: "Canada",
    price: "2100.00", bedrooms: 3, bathrooms: 2, area: "105.00", status: "available" as const, isFeatured: true,
    amenities: ["Garage", "Cour arrière", "Buanderie privée", "Cave"],
    images: ["https://picsum.photos/seed/apt4/800/500"],
    availableDates: ["2026-06-01", "2026-07-01"],
    nearbyPlaces: ["Marché Maisonneuve (400m)", "Métro Préfontaine (600m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 2 chambres Côte-des-Neiges",
    description: "Appartement bien situé près de l'Université de Montréal. Parfait pour étudiants ou famille.",
    type: "apartment" as const, city: "Montréal", address: "6780 Chemin de la Côte-des-Neiges", country: "Canada",
    price: "1550.00", bedrooms: 2, bathrooms: 1, area: "65.00", status: "rented" as const, isFeatured: false,
    amenities: ["Buanderie", "Chauffage inclus", "Métro proche"],
    images: ["https://picsum.photos/seed/apt5/800/500"],
    availableDates: [],
    nearbyPlaces: ["Université de Montréal (900m)", "Métro Côte-des-Neiges (400m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 3½ Vieux-Québec — vue fleuve",
    description: "Appartement de charme dans le Vieux-Québec avec vue partielle sur le fleuve. Pierres apparentes, poutres originales.",
    type: "apartment" as const, city: "Québec", address: "14 Rue Saint-Louis", country: "Canada",
    price: "1600.00", bedrooms: 1, bathrooms: 1, area: "58.00", status: "available" as const, isFeatured: true,
    amenities: ["Vue fleuve", "Cachet historique", "Chauffage inclus"],
    images: ["https://picsum.photos/seed/apt6/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["Château Frontenac (300m)", "Plaines d'Abraham (700m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 2 chambres Downtown Toronto",
    description: "Modern apartment with floor-to-ceiling windows in the heart of Downtown Toronto. Gym and concierge included.",
    type: "apartment" as const, city: "Toronto", address: "150 King St West, Unit 2204", country: "Canada",
    price: "2800.00", bedrooms: 2, bathrooms: 2, area: "85.00", status: "available" as const, isFeatured: true,
    amenities: ["Gym", "Concierge 24h", "Balcon", "Climatisation", "Stationnement"],
    images: ["https://picsum.photos/seed/apt7/800/500"],
    availableDates: ["2026-05-15", "2026-06-01"],
    nearbyPlaces: ["Union Station (400m)", "CN Tower (600m)", "PATH (100m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 1 chambre Griffintown",
    description: "Appartement contemporain dans le quartier branché de Griffintown. Accès rooftop, piscine extérieure.",
    type: "apartment" as const, city: "Montréal", address: "1000 Rue Wellington", country: "Canada",
    price: "1850.00", bedrooms: 1, bathrooms: 1, area: "52.00", status: "available" as const, isFeatured: false,
    amenities: ["Rooftop", "Piscine", "Gym", "Concierge"],
    images: ["https://picsum.photos/seed/apt8/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Métro Lucien-L'Allier (500m)", "Canal de Lachine (200m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 4½ — Laval proche Montréal",
    description: "Grand appartement familial à Laval avec terrain et stationnement double. 20 min de Montréal.",
    type: "apartment" as const, city: "Laval", address: "3400 Boul. Curé-Labelle", country: "Canada",
    price: "1650.00", bedrooms: 2, bathrooms: 1, area: "80.00", status: "available" as const, isFeatured: false,
    amenities: ["Stationnement double", "Terrain", "Buanderie privée"],
    images: ["https://picsum.photos/seed/apt9/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["Carrefour Laval (1km)", "Métro Montmorency (3km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Beau 2½ meublé — Mile-End",
    description: "Studio optimisé meublé et équipé dans le quartier Mile-End. Idéal pour nomade numérique.",
    type: "apartment" as const, city: "Montréal", address: "5280 Parc Avenue", country: "Canada",
    price: "1350.00", bedrooms: 1, bathrooms: 1, area: "42.00", status: "available" as const, isFeatured: false,
    amenities: ["Meublé", "Internet fibré", "Vélos disponibles"],
    images: ["https://picsum.photos/seed/apt10/800/500"],
    availableDates: ["2026-05-15"],
    nearbyPlaces: ["Marché Jean-Talon (800m)", "Parc Jeanne-Mance (400m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement 3 chambres — Vancouver West Side",
    description: "Bright and spacious 3-bedroom apartment in prestigious Vancouver West Side. Top-rated school district.",
    type: "apartment" as const, city: "Vancouver", address: "3200 W 10th Ave", country: "Canada",
    price: "3400.00", bedrooms: 3, bathrooms: 2, area: "98.00", status: "available" as const, isFeatured: true,
    amenities: ["Vue montagne", "Stationnement", "Buanderie en suite", "Cave"],
    images: ["https://picsum.photos/seed/apt11/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Kitsilano Beach (1km)", "UBC (3km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Appartement moderne 2½ — Calgary Downtown",
    description: "Modern studio loft in vibrant Calgary downtown. Walking distance to C-Train and all amenities.",
    type: "apartment" as const, city: "Calgary", address: "320 8th Ave SW", country: "Canada",
    price: "1550.00", bedrooms: 1, bathrooms: 1, area: "48.00", status: "available" as const, isFeatured: false,
    amenities: ["Gym", "Concierge", "Balcon", "Stationnement"],
    images: ["https://picsum.photos/seed/apt12/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["C-Train City Hall (400m)", "Calgary Tower (600m)"],
    ownerId: OWNER_ID,
  },

  /* ── MAISONS ── */
  {
    title: "Maison unifamiliale avec grande cour — Brossard",
    description: "Belle maison de ville sur 3 niveaux avec garage double et grand terrain. Quartier résidentiel calme près du REM.",
    type: "house" as const, city: "Brossard", address: "2345 Rue des Érables", country: "Canada",
    price: "3200.00", bedrooms: 4, bathrooms: 2, area: "185.00", status: "available" as const, isFeatured: true,
    amenities: ["Garage double", "Terrain 500m²", "Piscine creusée", "Buanderie"],
    images: ["https://picsum.photos/seed/house1/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["REM Panama (1,5km)", "DIX30 (3km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Maison de ville 3 chambres — Longueuil",
    description: "Maison semi-détachée très bien entretenue. Sous-sol aménagé, cour clôturée, proche du métro.",
    type: "house" as const, city: "Longueuil", address: "567 Rue Saint-Laurent", country: "Canada",
    price: "2400.00", bedrooms: 3, bathrooms: 2, area: "140.00", status: "available" as const, isFeatured: false,
    amenities: ["Sous-sol aménagé", "Cour clôturée", "Stationnement 2 voitures"],
    images: ["https://picsum.photos/seed/house2/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["Métro Longueuil (1km)", "Cégep Édouard-Montpetit (2km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Maison victorienne rénovée — Outremont",
    description: "Magnifique maison victorienne entièrement rénovée dans l'un des quartiers les plus prestigieux de Montréal.",
    type: "house" as const, city: "Montréal", address: "140 Avenue Bloomfield", country: "Canada",
    price: "5200.00", bedrooms: 5, bathrooms: 3, area: "280.00", status: "available" as const, isFeatured: true,
    amenities: ["Piscine", "Garage", "Jardin", "Bureau à domicile", "Climatisation"],
    images: ["https://picsum.photos/seed/house3/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Parc Outremont (500m)", "Université de Montréal (1km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Maison familiale 4 chambres — Laval",
    description: "Grande maison familiale avec sous-sol complet non aménagé et cour de 800m². Quartier avec parcs et écoles.",
    type: "house" as const, city: "Laval", address: "780 Rue des Peupliers", country: "Canada",
    price: "2800.00", bedrooms: 4, bathrooms: 2, area: "210.00", status: "available" as const, isFeatured: false,
    amenities: ["Sous-sol", "Garage simple", "Cour 800m²", "Buanderie"],
    images: ["https://picsum.photos/seed/house4/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["École primaire (400m)", "Parc de la Rivière-des-Milles-Îles (1km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Bungalow rénové — Québec (Sainte-Foy)",
    description: "Bungalow des années 70 entièrement mis à jour : cuisine neuve, salle de bain rénovée, fenêtres PVC.",
    type: "house" as const, city: "Québec", address: "2560 Avenue Lavigerie", country: "Canada",
    price: "2100.00", bedrooms: 3, bathrooms: 1, area: "120.00", status: "available" as const, isFeatured: false,
    amenities: ["Garage", "Terrain 400m²", "Buanderie"],
    images: ["https://picsum.photos/seed/house5/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Place Sainte-Foy (2km)", "Université Laval (1,5km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Maison détachée 5 chambres — North York, Toronto",
    description: "Spacious detached home in sought-after North York neighbourhood. Finished basement, backyard with deck.",
    type: "house" as const, city: "Toronto", address: "45 Bayview Ave", country: "Canada",
    price: "5800.00", bedrooms: 5, bathrooms: 3, area: "320.00", status: "available" as const, isFeatured: true,
    amenities: ["Sous-sol aménagé", "Terrasse", "Garage double", "Alarme"],
    images: ["https://picsum.photos/seed/house6/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["TTC Sheppard (600m)", "Fairview Mall (2km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Maison en rangée — Ottawa Hintonburg",
    description: "Stylish 3-bedroom row house in trendy Hintonburg. Walking distance to Wellington Street shops and restaurants.",
    type: "house" as const, city: "Ottawa", address: "312 Armstrong St", country: "Canada",
    price: "2900.00", bedrooms: 3, bathrooms: 2, area: "160.00", status: "available" as const, isFeatured: false,
    amenities: ["Cour arrière", "Stationnement", "Cave à vin"],
    images: ["https://picsum.photos/seed/house7/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["Marché By (3km)", "Colline du Parlement (4km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Maison moderne — Vancouver East",
    description: "Modern 4-bedroom half-duplex with rooftop deck and mountain views. Lane access parking.",
    type: "house" as const, city: "Vancouver", address: "1550 Commercial Drive", country: "Canada",
    price: "4500.00", bedrooms: 4, bathrooms: 3, area: "230.00", status: "available" as const, isFeatured: true,
    amenities: ["Toît-terrasse", "Vue montagne", "Parking arrière", "Buanderie"],
    images: ["https://picsum.photos/seed/house8/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Commercial-Broadway SkyTrain (400m)", "Trout Lake (1km)"],
    ownerId: OWNER_ID,
  },

  /* ── CONDOS ── */
  {
    title: "Condo haut de gamme — Vieux-Montréal",
    description: "Condo de luxe au 15e étage avec vue époustouflante sur le fleuve et le Vieux-Port. Finitions haut de gamme.",
    type: "apartment" as const, city: "Montréal", address: "650 Rue de la Commune Ouest", country: "Canada",
    price: "3800.00", bedrooms: 2, bathrooms: 2, area: "110.00", status: "available" as const, isFeatured: true,
    amenities: ["Vue fleuve", "Gym", "Piscine intérieure", "Spa", "Concierge 24h", "Stationnement"],
    images: ["https://picsum.photos/seed/condo1/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Vieux-Port (200m)", "Métro Square-Victoria (600m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Condo neuf 2 chambres — Quartier Dix30, Brossard",
    description: "Condo dans une tour neuve près du REM. Finitions contemporaines, grande terrasse, stationnement souterrain.",
    type: "apartment" as const, city: "Brossard", address: "9160 Boul. Leduc", country: "Canada",
    price: "2200.00", bedrooms: 2, bathrooms: 2, area: "90.00", status: "available" as const, isFeatured: false,
    amenities: ["Terrasse", "Gym", "Stationnement", "Casier de rangement"],
    images: ["https://picsum.photos/seed/condo2/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["REM DIX30 (300m)", "Quartier DIX30 (400m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Penthouse 3 chambres — Square Phillips",
    description: "Penthouse d'exception sur 2 niveaux avec terrasse privative de 200m² et vue à 360° sur Montréal.",
    type: "apartment" as const, city: "Montréal", address: "1188 Square Phillips", country: "Canada",
    price: "7500.00", bedrooms: 3, bathrooms: 3, area: "250.00", status: "available" as const, isFeatured: true,
    amenities: ["Terrasse privée 200m²", "Vue 360°", "Gym", "Piscine", "Concierge", "2 stationnements"],
    images: ["https://picsum.photos/seed/condo3/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Métro McGill (300m)", "Place des Arts (800m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Condo 1 chambre — Yaletown, Vancouver",
    description: "Bright 1-bedroom condo in iconic Yaletown. Open concept with exposed brick and concrete finishes.",
    type: "apartment" as const, city: "Vancouver", address: "1255 Seymour St, Unit 1402", country: "Canada",
    price: "2900.00", bedrooms: 1, bathrooms: 1, area: "62.00", status: "available" as const, isFeatured: true,
    amenities: ["Vue ville", "Gym", "Concierge", "Balcon"],
    images: ["https://picsum.photos/seed/condo4/800/500"],
    availableDates: ["2026-05-15"],
    nearbyPlaces: ["False Creek (300m)", "SkyTrain Yaletown (400m)"],
    ownerId: OWNER_ID,
  },

  /* ── CO-LIVING / COLOCATION ── */
  {
    title: "Chambre meublée en colocation — Mile End",
    description: "Chambre privée dans un loft de 4 colocataires. Espaces communs modernes, Wifi ultra-rapide, proche transports.",
    type: "co-living" as const, city: "Montréal", address: "5680 Avenue du Parc", country: "Canada",
    price: "850.00", bedrooms: 1, bathrooms: 1, area: "22.00", status: "available" as const, isFeatured: false,
    amenities: ["Meublé", "Internet fibré", "Cuisine équipée", "Lave-linge", "Netflix partagé"],
    images: ["https://picsum.photos/seed/coliv1/800/500"],
    availableDates: ["2026-05-15"],
    nearbyPlaces: ["Métro Laurier (600m)", "Marché Jean-Talon (1km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Chambre en colocation — Plateau, Montréal",
    description: "Grande chambre avec penderie dans appartement de 3 colocataires. Toutes charges incluses, ambiance conviviale.",
    type: "co-living" as const, city: "Montréal", address: "4230 Rue Rachel Est", country: "Canada",
    price: "780.00", bedrooms: 1, bathrooms: 1, area: "18.00", status: "available" as const, isFeatured: false,
    amenities: ["Charges incluses", "Meublé", "Balcon partagé"],
    images: ["https://picsum.photos/seed/coliv2/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Parc La Fontaine (500m)", "Métro Sherbrooke (700m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Coliving étudiant — Côte-des-Neiges",
    description: "Résidence étudiante privée avec chambre meublée. Idéal pour étudiants UdeM ou HEC. Services inclus.",
    type: "co-living" as const, city: "Montréal", address: "7120 Chemin Queen-Mary", country: "Canada",
    price: "920.00", bedrooms: 1, bathrooms: 1, area: "20.00", status: "available" as const, isFeatured: false,
    amenities: ["Meublé", "Internet", "Nettoyage hebdo", "Salle d'étude", "Salle de sport"],
    images: ["https://picsum.photos/seed/coliv3/800/500"],
    availableDates: ["2026-09-01"],
    nearbyPlaces: ["Université de Montréal (500m)", "HEC Montréal (800m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Chambre en co-living — Downtown Toronto",
    description: "Private room in modern co-living space. All bills included. Common areas with standing desks and fast WiFi.",
    type: "co-living" as const, city: "Toronto", address: "600 King St West, Unit 3B", country: "Canada",
    price: "1350.00", bedrooms: 1, bathrooms: 1, area: "24.00", status: "available" as const, isFeatured: false,
    amenities: ["Meublé", "Tout inclus", "Co-working", "Gym partagé"],
    images: ["https://picsum.photos/seed/coliv4/800/500"],
    availableDates: ["2026-05-15"],
    nearbyPlaces: ["TTC King (200m)", "Rogers Centre (1km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Chambre meublée colocation — Québec Haute-Ville",
    description: "Chambre dans superbe colocation 3 personnes en Haute-Ville. Appartement spacieux, charges incluses.",
    type: "co-living" as const, city: "Québec", address: "456 Grande Allée Est", country: "Canada",
    price: "720.00", bedrooms: 1, bathrooms: 1, area: "16.00", status: "available" as const, isFeatured: false,
    amenities: ["Meublé", "Charges incluses", "Stationnement"],
    images: ["https://picsum.photos/seed/coliv5/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Plaines d'Abraham (300m)", "Assemblée nationale (500m)"],
    ownerId: OWNER_ID,
  },

  /* ── BUREAUX (OFFICE) ── */
  {
    title: "Bureau cloisonné 6 postes — McGill College",
    description: "Bureau privé dans immeuble classe A au cœur du CBD montréalais. Accès à salle de réunion partagée.",
    type: "office" as const, city: "Montréal", address: "1000 Rue de la Gauchetière Ouest, Suite 400", country: "Canada",
    price: "4200.00", bedrooms: null, bathrooms: 2, area: "120.00", status: "available" as const, isFeatured: true,
    amenities: ["Salle de réunion", "Réception", "Cuisine partagée", "Climatisation", "Fibre optique"],
    images: ["https://picsum.photos/seed/office1/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Métro McGill (200m)", "Place Ville Marie (500m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Open-space 20 postes — Griffintown",
    description: "Grand plateau bureaux open-space entièrement équipé dans le quartier des startups montréalaises.",
    type: "office" as const, city: "Montréal", address: "225 Rue Notre-Dame Ouest", country: "Canada",
    price: "8500.00", bedrooms: null, bathrooms: 3, area: "320.00", status: "available" as const, isFeatured: true,
    amenities: ["Open-space", "3 salles de réunion", "Cuisine", "Terrasse", "Fibre 1Gbps"],
    images: ["https://picsum.photos/seed/office2/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Canal de Lachine (200m)", "Métro Lucien-L'Allier (700m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Bureau privé 4 postes — Vieux-Québec",
    description: "Bureau calme et lumineux dans maison de ville rénovée. Idéal pour petite équipe ou bureau satellite.",
    type: "office" as const, city: "Québec", address: "78 Rue Saint-Pierre", country: "Canada",
    price: "2800.00", bedrooms: null, bathrooms: 1, area: "85.00", status: "available" as const, isFeatured: false,
    amenities: ["Bureau privé", "Internet", "Salle de réunion", "Parking"],
    images: ["https://picsum.photos/seed/office3/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["Port de Québec (400m)", "Vieux-Québec (300m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Bureau executive 2 postes — Bay St, Toronto",
    description: "Prestigious executive office suite in iconic Bay Street tower. Impressive reception, city views.",
    type: "office" as const, city: "Toronto", address: "200 Bay St, Suite 3100", country: "Canada",
    price: "6500.00", bedrooms: null, bathrooms: 1, area: "95.00", status: "available" as const, isFeatured: true,
    amenities: ["Vue ville", "Réception", "Salle de réunion", "Concierge"],
    images: ["https://picsum.photos/seed/office4/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Union Station (500m)", "Toronto Stock Exchange (200m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Bureau coworking 8 postes — Calgary",
    description: "Coworking space premium avec postes dédiés. Accès 24/7, café illimité, salles de meeting équipées.",
    type: "office" as const, city: "Calgary", address: "112 4th Ave SW", country: "Canada",
    price: "3800.00", bedrooms: null, bathrooms: 2, area: "140.00", status: "available" as const, isFeatured: false,
    amenities: ["Accès 24/7", "Café inclus", "Salles réunion", "Impression"],
    images: ["https://picsum.photos/seed/office5/800/500"],
    availableDates: ["2026-05-15"],
    nearbyPlaces: ["C-Train Centre (400m)", "Calgary Tower (700m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Bureau partagé — Ottawa Centre",
    description: "Bureau partagé dans espace de coworking gouvernemental-friendly. Certifié sécurité Niveau 2.",
    type: "office" as const, city: "Ottawa", address: "150 Elgin St, 8e étage", country: "Canada",
    price: "3200.00", bedrooms: null, bathrooms: 2, area: "110.00", status: "available" as const, isFeatured: false,
    amenities: ["Sécurité renforcée", "Salles de réunion", "Cuisine", "Parking"],
    images: ["https://picsum.photos/seed/office6/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["Colline du Parlement (500m)", "Centre Rideau (1km)"],
    ownerId: OWNER_ID,
  },

  /* ── COMMERCIAL ── */
  {
    title: "Local commercial — Rue Sainte-Catherine",
    description: "Excellent emplacement sur l'artère commerciale principale de Montréal. Grande vitrine, 2 entrées, cave.",
    type: "commercial" as const, city: "Montréal", address: "1450 Rue Sainte-Catherine Ouest", country: "Canada",
    price: "6800.00", bedrooms: null, bathrooms: 1, area: "180.00", status: "available" as const, isFeatured: true,
    amenities: ["Grande vitrine", "Cave", "Accès livraison", "Aire de vente 150m²"],
    images: ["https://picsum.photos/seed/comm1/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Métro Guy-Concordia (300m)", "Centre commercial Les Ailes (500m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Local commercial angle — Plateau",
    description: "Local en angle avec 2 façades vitrées idéal pour boutique, café ou salon. Quartier très achalandé.",
    type: "commercial" as const, city: "Montréal", address: "4012 Rue Mont-Royal Est", country: "Canada",
    price: "4200.00", bedrooms: null, bathrooms: 1, area: "120.00", status: "available" as const, isFeatured: false,
    amenities: ["2 façades", "Local livraison", "Cave"],
    images: ["https://picsum.photos/seed/comm2/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["Métro Mont-Royal (400m)", "Marché Plateau (200m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Entrepôt industriel — Zone Saint-Laurent",
    description: "Entrepôt logistique avec quai de déchargement, grand stationnement et bureaux intégrés.",
    type: "commercial" as const, city: "Montréal", address: "8850 Boul. Cavendish", country: "Canada",
    price: "9500.00", bedrooms: null, bathrooms: 2, area: "850.00", status: "available" as const, isFeatured: false,
    amenities: ["Quai de chargement", "Stationnement 20 véhicules", "Bureaux intégrés", "Hauteur libre 8m"],
    images: ["https://picsum.photos/seed/comm3/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["Autoroute 40 (500m)", "Zone industrielle Saint-Laurent"],
    ownerId: OWNER_ID,
  },
  {
    title: "Restaurant clé en main — Vieux-Montréal",
    description: "Local restauration entièrement équipé : hotte, chambre froide, terrasse privative, licence alcool en cours.",
    type: "commercial" as const, city: "Montréal", address: "350 Place Jacques-Cartier", country: "Canada",
    price: "8200.00", bedrooms: null, bathrooms: 2, area: "220.00", status: "available" as const, isFeatured: true,
    amenities: ["Cuisine professionnelle", "Terrasse 40 couverts", "Chambre froide", "Bar"],
    images: ["https://picsum.photos/seed/comm4/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["Vieux-Port (100m)", "Basilique Notre-Dame (300m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Local commercial — Rue Wellington, Toronto",
    description: "Retail space in booming King West neighbourhood. High foot traffic, flexible layout, rear laneway access.",
    type: "commercial" as const, city: "Toronto", address: "640 King St West", country: "Canada",
    price: "7500.00", bedrooms: null, bathrooms: 1, area: "200.00", status: "available" as const, isFeatured: true,
    amenities: ["Grande vitrine", "Accès ruelle", "Mezzanine"],
    images: ["https://picsum.photos/seed/comm5/800/500"],
    availableDates: ["2026-06-01"],
    nearbyPlaces: ["TTC King (300m)", "TIFF Bell Lightbox (500m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Boutique / Galerie — Quartier Petit-Champlain, Québec",
    description: "Charmant local commercial dans le quartier touristique le plus visité du Québec. Idéal pour galerie ou boutique.",
    type: "commercial" as const, city: "Québec", address: "42 Rue du Petit-Champlain", country: "Canada",
    price: "3800.00", bedrooms: null, bathrooms: 1, area: "90.00", status: "available" as const, isFeatured: false,
    amenities: ["Cachet historique", "Vitrine", "Cave"],
    images: ["https://picsum.photos/seed/comm6/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["Château Frontenac (800m)", "Funiculaire (200m)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Local mixte activités — Vancouver East",
    description: "Flexible light industrial / commercial unit with grade-level loading door. Great for studio, workshop or showroom.",
    type: "commercial" as const, city: "Vancouver", address: "1820 Franklin St", country: "Canada",
    price: "4800.00", bedrooms: null, bathrooms: 1, area: "280.00", status: "available" as const, isFeatured: false,
    amenities: ["Porte de chargement", "Hauteur libre 5m", "Bureaux", "Stationnement"],
    images: ["https://picsum.photos/seed/comm7/800/500"],
    availableDates: ["2026-06-15"],
    nearbyPlaces: ["Commercial Drive (500m)", "Port de Vancouver (2km)"],
    ownerId: OWNER_ID,
  },
  {
    title: "Espace commercial — Rue Laurier Ouest",
    description: "Local lumineux sur artère branchée d'Outremont. Parfait pour boutique mode, épicerie fine ou salon de beauté.",
    type: "commercial" as const, city: "Montréal", address: "1090 Avenue Laurier Ouest", country: "Canada",
    price: "5200.00", bedrooms: null, bathrooms: 1, area: "150.00", status: "available" as const, isFeatured: false,
    amenities: ["Grande vitrine", "Terrasse potentielle", "Stationnement rue"],
    images: ["https://picsum.photos/seed/comm8/800/500"],
    availableDates: ["2026-07-01"],
    nearbyPlaces: ["Métro Laurier (600m)", "Parc Outremont (400m)"],
    ownerId: OWNER_ID,
  },
];

async function main() {
  console.log(`🌱  Début du seed — ${seed.length} annonces à insérer...`);

  /* Vider la table des biens existants créés par le seed (pour éviter les doublons) */
  await db.delete(propertiesTable).where(sql`owner_id = ${OWNER_ID}`);
  console.log("   ✓ Anciens enregistrements seed supprimés");

  /* Insérer en lot */
  const inserted = await db.insert(propertiesTable).values(seed).returning({ id: propertiesTable.id, title: propertiesTable.title, type: propertiesTable.type, city: propertiesTable.city });

  /* Statistiques par catégorie */
  const byType: Record<string, number> = {};
  for (const p of inserted) {
    byType[p.type] = (byType[p.type] ?? 0) + 1;
  }

  console.log(`\n✅  ${inserted.length} annonces insérées avec succès !\n`);
  console.log("📊  Répartition par catégorie :");
  for (const [type, count] of Object.entries(byType)) {
    console.log(`   • ${type.padEnd(12)} : ${count} annonces`);
  }

  const cities = [...new Set(inserted.map(p => p.city))].sort();
  console.log(`\n🏙️   Villes couvertes : ${cities.join(", ")}`);
  process.exit(0);
}

main().catch((err) => {
  console.error("❌ Erreur lors du seed :", err);
  process.exit(1);
});
