// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bloq5-redesign/Homepage.tsx": () => import("../components/mockups/bloq5-redesign/Homepage.tsx"),
  "./components/mockups/bloq5-redesign/Properties.tsx": () => import("../components/mockups/bloq5-redesign/Properties.tsx")
};
